### ISSUE TITLE
Update to ESLint 1.0.0

### ISSUE THREAD

**Issue by IanVS** [IanVS/eslint-nibble#10]

**Comment by zdychacek** [comment]
+1

**Comment by IanVS** [comment]
I am going to try to get #12 in place before upgrading to `1.0.0`.  The difficult part is mostly done, will try to finish it up tomorrow and push a `1.0.0` version of this package which includes eslint `1.0.0` by the end of this week.  

I am also considering releasing another version of this tool which will peer-depend on ESLint for those who want to update ESLint independently of this tool.  Hopefully some of the architecture changes I've made in #12 will make that feasible.

**Comment by IanVS** [comment]
This is closed by https://github.com/IanVS/eslint-nibble/commit/383b042c64f0f4fa646e9c81dedbeca17c4b694e.
