### ISSUE TITLE
ignore not found glob pattern?

### ISSUE THREAD

**Issue by jd0gx** [IanVS/eslint-nibble#105]
```
$ eslint-nibble --ext .jsx,.js,.tsx,.ts ./src/**/* ./src-api/**/* ./src-shared/**/*
```

As you can see.   './src/img/auth' is an image folder. It does not make sense to raise an error here.

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/4531670/226091600-0213be11-6126-4a2f-b22f-afb52c223a09.png">

<img width="298" alt="image" src="https://user-images.githubusercontent.com/4531670/226091651-714fe832-900d-4cf1-a6a4-70c2dca5b573.png">

**Comment by IanVS** [comment]
I believe your shell is expanding the globs into a list of arguments.  You could try quoting each glob to prevent that behavior, or you could just provide the folder names: `eslint-nibble --ext .jsx,.js,.tsx,.ts src src-api src-shared`

**Comment by jd0gx** [comment]
I tried quoting them and it didn't work.

I end up expanding them manually `eslint-nibble ./src/**/*.ts ./src/**/*.tsx ...`

**Comment by jd0gx** [comment]
` eslint-nibble --ext .jsx,.js,.tsx,.ts src src-api src-shared` do work! Thanks!
