### ISSUE TITLE
Thoughts on moving away from `eslint-summary`?

### ISSUE THREAD

**Issue by TheBox193** [IanVS/eslint-nibble#107]
# Background
[`eslint-summary`](https://github.com/davidwaterston/eslint-summary) provides the summary line for `eslint-nibble`.
![image](https://user-images.githubusercontent.com/220755/230822681-530510d9-caee-465e-b714-d5af3e9a0ae7.png)

While `eslint-nibble` has been maintained, `eslint-summary` has not for ~8yrs. For example `eslint-nibble` is using `"chalk": "^4.1.1"` while `eslint-summary` is still on  "chalk": "^1.0.0".

The functionality of `eslint-summary` is rather [straightforward](https://github.com/davidwaterston/eslint-summary/blob/master/summary.js). Does it make sense to adopt and pull this code into `eslint-nibble`?

This came to my attention when looking through my repos dependencies and vulnerabilities and chasing down where older versions of `chalk` where coming from.

# Thoughts?
I would be happy to open a PR & add some unit tests if there is interest. 🙂

**Comment by IanVS** [comment]
That sounds like a good idea.  Normally I'd suggest submitting a PR upstream, but the author has not been on GitHub for years it looks like, so I think that would be fruitless.  I'd be happy to accept a PR that pulls it into eslint-nibble itself.  Thanks for the offer.
