### ISSUE TITLE
Support `--ext` command line argument

### ISSUE THREAD

**Issue by tlrobinson** [IanVS/eslint-nibble#21]
Unfortunately there's no way to configure which extensions to look at in `.eslintrc` so you have to pass it on the command line: http://eslint.org/docs/user-guide/configuring#specifying-file-extensions-to-lint

It would be great if nibble supported this so I could use it on `.jsx` files, etc.

Relevant ESLint issue: https://github.com/eslint/eslint/issues/2419

**Comment by IanVS** [comment]
Thanks for the report. I'll work on it tonight, but in the meantime maybe
you can use a glob pattern like `*.jsx`?

**Comment by IanVS** [comment]
Published version `2.1.0` to support `--ext`.  But, version `3.0.0` is right around the corner, which will add support for ESLint 3.X, so I'd suggest waiting for that version if you can.

**Comment by tlrobinson** [comment]
Thanks for being so responsive!
