### ISSUE TITLE
Allow a custom .eslintrc file

### ISSUE THREAD

**Issue by aboyton** [IanVS/eslint-nibble#27]
For our project we have two `.eslintrc`files, `.eslintrc` which is what we're currently enforcing and `.eslintrc.next`which is where we'd like to be.

It would be nice if you could pass in a custom `.eslintrc` file to nibble like you can with ESLint—`eslint -c .eslintrc.next`.

**Comment by IanVS** [comment]
Seems reasonable.  Would you like to submit a PR?  Should just be a matter of adding the option to https://github.com/IanVS/eslint-nibble/blob/master/src/config/options.js, and then adding some flexibility around https://github.com/IanVS/eslint-nibble/blob/master/src/nibbler.js#L62 which is called from https://github.com/IanVS/eslint-nibble/blob/master/src/cli.js#L35.  I'll try to get to it within the next week or so if you're not able.

**Comment by aboyton** [comment]
I've had my first go at making a pull request to try an implement this. Please let me know if this works or not.
