### ISSUE TITLE
Ability to define eslint rules

### ISSUE THREAD

**Issue by rajsekhar3g** [IanVS/eslint-nibble#43]
I have a .eslintrc file in my project with all the required rules. However, when running this it seems to ignore that file and display some standard errors based on what it thinks are the rules. How can i force it to use my set of rules?

**Comment by IanVS** [comment]
Hi @rajsekhar3g.  How do you have `eslint-nibble` installed (locally or globally)?  Can you give some examples of what is happening?  Putting a valid config file in your project directory should be enough to cause the correct rules to be used.  The more information you can provide, the more likely we can figure out the cause.

**Comment by rajsekhar3g** [comment]
i have it installed using --save-dev flag. i have a .eslintrc file with some rules and when i run eslint, i get 4 errors. however with the eslint-nibble i get 2225 errors which doesnt make any sense, unless it has its own set of rules and doesnt obey .eslintrc. is there a way to set the file. what does it do when there isnt a file

**Comment by rajsekhar3g** [comment]
This was not an issue with eslint-nibble. My eslint was doing a dry run fix hiding some of the errors.

**Comment by IanVS** [comment]
Ah, great.  Glad you got it figured out!  Thanks for posting back to let us know.
