### ISSUE TITLE
`npx eslint-nibble` fails, because it uses `require`

### ISSUE THREAD

**Issue by ljharb** [IanVS/eslint-nibble#45]
Instead of using bare `require`, eslint-nibble should use `require(resolve(path, { cwd: process.cwd() }))` and https://npmjs.com/resolve, so it doesn't have to be installed locally.

**Comment by IanVS** [comment]
Interesting, I hadn't seen that before.  I'll try it out.

**Comment by IanVS** [comment]
I just tried a `npx --ignore-existing --no-install eslint-nibble bar.js` and it _seemed_ to work just fine.  Is this still an issue, or has `npx` improved to the point where it works with no changes to this package?

**Comment by ljharb** [comment]
It shouldn’t need those flags to work tho.

**Comment by IanVS** [comment]
Hm, this is still broken in `5.0.0-beta.1`.  I'm seeing:

```
Cannot find module 'eslint' from '/Users/ianvs/.npm/_npx/14964/lib/node_modules/eslint-nibble/lib'
```

I don't think it likes that eslint is a peer dependency.  🙄

**Comment by IanVS** [comment]
Unfortunately I couldn't get this working right now, so I backed it out from the upcoming 5.0 release.  I'll try to spend some more time on it after 5.0 is out, but I don't want this to hold things up.

**Comment by sibelius** [comment]
I've got the same problem

what if eslint-nibble have its own eslint package?

I think this issue would be solved

**Comment by IanVS** [comment]
@sibelius, in fact it did come shipped with its own version of eslint up until 5.0, but that causes other problems.  As a workaround until `npx` can properly support peer-dependencies, I'd suggest using `npm install --no-save eslint-nibble` as noted in the readme.

**Comment by jaacko-torus** [comment]
I loved this utility, I took a break from js for a year or so and now I come back and I'm getting this error. Is there any chance that this will be fixed?

**Comment by IanVS** [comment]
Hi, do you know if npx supports peer dependencies now?  If so, I could take a shot at it.  Or even better, I'd love to review a PR if you or someone else is able to put one together.

**Comment by ljharb** [comment]
I don’t think it does automatically, but you could probably craft an npx command that works.

**Comment by IanVS** [comment]
I just tried running `npx eslint-nibble .` in one of my projects, and it worked just fine.  Maybe npx has made improvements.  I'm going to close this out, but speak up if you still experience problems.
