### ISSUE TITLE
Pass rule(s) as a CLI flag?

### ISSUE THREAD

**Issue by ljharb** [IanVS/eslint-nibble#47]
I'd love to be able to pre-select the rule[(s)](#46) with `--rule` or similar, so I can skip the laborious list navigation :-)

**Comment by IanVS** [comment]
That sounds reasonable.

**Comment by IanVS** [comment]
Closed by https://github.com/IanVS/eslint-nibble/commit/58d09cafe1ba91054dab4a5384aa017e28827c6d, released in `5.0.0-beta.4`
