### ISSUE TITLE
Fixes all issues when selecting only one rule

### ISSUE THREAD

**Issue by nisevi** [IanVS/eslint-nibble#55]
When selecting a particular rule to be fixed:

![image](https://user-images.githubusercontent.com/3024789/54694015-59345680-4b06-11e9-873e-8becaa0d6f2e.png)

It will ask for confirmation:

![image](https://user-images.githubusercontent.com/3024789/54694073-6c472680-4b06-11e9-8034-b38313ef4a94.png)

![image](https://user-images.githubusercontent.com/3024789/54694118-79641580-4b06-11e9-9230-38b71118ff0e.png)

And after hitting enter it will fix all issues, not just the one that I have chosen.

Any ideas of why this could be happening?

My `package.json` looks like:

```
"nibble": "eslint-nibble --ext .jsx,.js client/"
```

**Comment by IanVS** [comment]
I just now saw this, sorry for the delay.  I'm not quite sure what's going on, but I can look into it.  What version of eslint are you using?

**Comment by nisevi** [comment]
@IanVS the versions I'm using are:

```
    "babel-eslint": "^7.2.2",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-react": "^7.1.0",
```

This is what I have in my `package.json` file.

**Comment by IanVS** [comment]
Hi @nisevi, thanks.  The peer dependency of eslint-nibble on eslint is 4.0 or above.  Are you able to upgrade your eslint to a more recent version?

**Comment by ljharb** [comment]
(specifically, unless `npm ls` exits successfully, you won’t be able to rely on anything working properly)

**Comment by nisevi** [comment]
Thank you for your time @IanVS and @ljharb I will try to upgrade the project for using eslint 4.0 👍
