### ISSUE TITLE
Avoid interactive questions to autofix one --rule

### ISSUE THREAD

**Issue by viT-1** [IanVS/eslint-nibble#57]
From [this documentation](https://github.com/IanVS/eslint-nibble/pull/35/commits/c4c895bbd52067da5c44039ce4103b60b20dab66) is not clear how to avoid node.js interactive and autofix errors & warnings for command: `eslint-nibble ./src/**/*.ts --rule comma-dangle`

How to preset answers "Enter, y, y"?

**Comment by IanVS** [comment]
Hi @viT-1, what use case do you have for this?  The whole point of eslint-nibble is to give an interactive display and menu when fixing eslint rules.  If you just want to fix a particular rule, you can run `eslint --fix` directly.  https://eslint.org/docs/user-guide/command-line-interface#fixing-problems

**Comment by ljharb** [comment]
That may not be entirely accurate, because afaik there’s no way to use eslintrc (for settings, parser options, default rule configs, etc) while disabling all rules except the ones enabled on the command line.

**Comment by IanVS** [comment]
Ah, good point.  In that case, I'd suggest taking a look at https://github.com/ianvs/eslint-filtered-fix and seeing if that would meet your needs, @viT-1.  It's what eslint-nibble uses under-the-hood.
