### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by kobik** [IanVS/eslint-nibble#64]
Hi @IanVS, thanks for this package.

Any ETA on the next npm release which should include the new CLI flags such as `--no-interactive`?

**Comment by IanVS** [comment]
Hi @kobik, thanks for the interest.  I'm happy to cut a new major release, but would you mind trying out the beta first to ensure it does what you need it to?  I haven't gotten any feedback on it so far, and I'd love if someone could try it out.  You can install it using `eslint-nibble@next`.

**Comment by kobik** [comment]
installing using `npm i -g eslint-nibble@next` resulted in
`eslint-nibble@5.0.0-beta.4`, so i installed `npm i -g eslint-nibble@beta`
which resulted in `eslint-nibble@6.0.0-beta.0`.

anyway, when i ran `eslint-nibble app --cache --no-interactive --rule
'security/detect-object-injection'` it didn't respect the rule, which could
be probably by design, but not exactly what i wanted.

what i wanted to achieve is scanning for a specific rule(s) only in CI.

**Comment by IanVS** [comment]
Ah, sorry for that confusion, glad you figured it out.  As for the problem you're seeing, it looks like you installed eslint-nibble globally.  Do you also have eslint and the `security` plugin installed globally?  That's not how I suggest installing this package, so there might be some bugs when running it that way.  Is there a reason you can't install it into the project that you're running against CI?

**Comment by ljharb** [comment]
Why would you need a new major if there’s just new stuff? Usually that’s a minor.

Also, eslint 7 is out; it’d be great to ensure eslint-nibble works with it.

**Comment by kobik** [comment]
@IanVS, this was just for a quick test locally on my mac. We do want to use as local install.

Still when running the command
```bash
node_modules/.bin/eslint-nibble app --cache --no-interactive --rule 'security/detect-object-injection'
```
results on returning errors for all of the rules.

It it by design?

**Comment by IanVS** [comment]
@ljharb I need a major because of updates to dependencies dropping support for node less than 8.  

@kobik thanks for testing it out.  It seems there may be a bug using `--no-interactive` and `--rule` together.  https://github.com/IanVS/eslint-nibble/issues/67. I will try to take a look soon, sorry for the delay.

**Comment by IanVS** [comment]
[6.0.0](https://github.com/IanVS/eslint-nibble/releases/tag/v6.0.0) has been released.
