### ISSUE TITLE
Combination --no-interactive and --rule does not work

### ISSUE THREAD

**Issue by romanvbabenko** [IanVS/eslint-nibble#67]
Version: v6.0.0-beta.0
Node: 12
System: OSX Catalina

For instance: 
`
 yarn eslint-nibble --no-interactive --rule semi file.js`

shows just everything with 

`
error Command failed with exit code 1.
`

**Comment by IanVS** [comment]
This is fixed in version 6.0.0.  Thanks for the report.  Please let me know if you have any other problems.
