### ISSUE TITLE
Add `--fix` flag to combine with `--no-interactive`

### ISSUE THREAD

**Issue by romanvbabenko** [IanVS/eslint-nibble#74]
yarn eslint-nibble --rule quotes --no-interactive --fix .

```
Invalid option '--fix' - perhaps you meant '-f'?
```

**Comment by IanVS** [comment]
Sorry, that's not one of the eslint-nibble flags.  What use-case do you have for this?  You just want to fix a single rule without the interactive chooser?

**Comment by romanvbabenko** [comment]
Exactly. If it can be done in interactive mode I'd be great to have it in non-interactive one as well.
For instance in Ruby linter tool RuboCop can do that from the box 
```
rubocop app/controllers/users_controller.rb --only Layout/ExtraSpacing -a
```
so I'm looking the same functionality tool for js part

**Comment by IanVS** [comment]
Hmmm, I'll need to think about it.  The original goal of `--no-interactive` was simply to enable use in CI, but your case makes sense too.  In fact, eslint-nibble uses https://github.com/IanVS/eslint-filtered-fix under the hood, and I think it could meet your needs nicely.  Maybe try it out and let me know what you think?

**Comment by bdefore** [comment]
would also like to see this. interactive mode is particularly challenging on a large project where if there is more than one page worth of rule options, it will redraw for each cursor movement.

**Comment by IanVS** [comment]
Have you tried using https://github.com/IanVS/eslint-filtered-fix for this, @bdefore?

**Comment by bdefore** [comment]
i have not yet

**Comment by bdefore** [comment]
indeed it does. thanks for your work on these libraries.

**Comment by IanVS** [comment]
I'd be happy to review a PR to update the cli options of filtered-fix!
