### ISSUE TITLE
package.lock.json size

### ISSUE THREAD

**Issue by egracens** [IanVS/eslint-nibble#84]
It is not an issue. Just wondering. Is it OK that package.lock.json has a size of 13k lines?

**Comment by ljharb** [comment]
Yes, it’s ok and expected, and has nothing to do with this repo specifically.

**Comment by egracens** [comment]
There are 916 lines of JS code and 13k lines of dependencies in this repo. If it is OK for JS projects in general then we live in the mad world 😄

![image](https://user-images.githubusercontent.com/10169850/132354566-a43d372e-4a2b-4d1e-bffd-b2b662e03c56.png)

**Comment by IanVS** [comment]
That's not _quite_ accurate.  I'm sure there are many more lines of javascript in the dependencies, but I'm guessing the tool you ran does not include `node_modules`.  The `package.lock.json` file describes the dependencies, and you can learn more about it at https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json.  

Another thing to keep in mind, many of those dependencies are development tools, and are not used in the actual runtime of eslint-nibble.  

But at the end of the day, this isn't a meme for no reason:

![image](https://user-images.githubusercontent.com/4616705/132356336-7b08d82f-a336-4e59-a342-008388243566.png)

**Comment by ljharb** [comment]
More deps is better :-)
