### ISSUE TITLE
Can I skip selecting an rule to "fix"?

### ISSUE THREAD

**Issue by Stargator** [IanVS/eslint-nibble#85]
> Select one of the rules by arrowing up/down and pressing enter

What can I do at this stage if I don't want to fix anything. I just wanted to see a report.

**Comment by IanVS** [comment]
Normally I just kill the process with `ctrl+c`.  I can see if there's a nicer way to do that though...

**Comment by IanVS** [comment]
Yeh, seems like ctrl + c is the way to go.  It was suggested to allow escape at one time, but that was decided against. https://github.com/SBoudrias/Inquirer.js/issues/148
