### ISSUE TITLE
Avoid strictive rules using `eslint-nibble`

### ISSUE THREAD

**Issue by brunolnetto** [IanVS/eslint-nibble#92]
Hi Ian,

I am pleased to endorse this package. ESLint is a necessary package. On available packages, the errors are not easy to treat one by one. At this moment, I fix all [my](https://github.com/dot-quiver/dot-quiver-api) lint-ycal issues. 

I would like to ask/suggest a feature: given the .eslintrc config file, how is it possible to avoid some specific rule by using `eslint-nibble`? Typically, as seen below, eslint extends some specific indentation style in my case 'airbnb-base'. Sometimes there is a rule one wants to avoid because it is too strict, for example, the `camelcase` rule on the image below.

```
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'airbnb-base',
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  rules: {
  },
};
```

![image](https://user-images.githubusercontent.com/13961685/150966965-de66fb5e-a1bf-4611-b747-bcf47254742f.png)

**Comment by IanVS** [comment]
Hi, are you asking how to configure eslint to ignore that rule, or only eslint-nibble?  There's no way to hide it from eslint-nibble only, but you can turn it off on your eslint config in the `rules`  section, like this:

```js

rules: {
  camelcase: "off",
}
```

**Comment by brunolnetto** [comment]
Nice! I am very pleased to use the library. Thank you!

**Comment by brunolnetto** [comment]
I did as you mentioned, but the camelcase option still appears on my eslint-nibble menu. The resulting `.eslintrc.cjs` content is below.

```
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'airbnb-base',
  ],
  rules: {
    camelcase: "off",
  },
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  rules: {
  },
};

```
