### ISSUE TITLE
Fix all fixable eslint issues

### ISSUE THREAD

**Issue by brunolnetto** [IanVS/eslint-nibble#93]
Since fixable eslint issues may be hand by hand fixed, a natural feature is to allow users to have the option to autofix all fixable ones.

**Comment by IanVS** [comment]
That can be done by eslint without the need for eslint-nibble.  https://eslint.org/docs/user-guide/command-line-interface#fixing-problems

This tool isn't meant to replace eslint, but rather add some functionality to it, specifically focusing on one rule at a time.

**Comment by brunolnetto** [comment]
Nice. Thank you for the quick answer!
