### ISSUE TITLE
Jest statements `no-undef` eslint error

### ISSUE THREAD

**Issue by brunolnetto** [IanVS/eslint-nibble#94]
The test framework _Jest_ is very useful for programmers. However, eslint dislikes its statements: `it`, `expect`, `describe` and `beforeEach`, among others. Maybe I am asking in the wrong place, I ask you to say if so:

Is the a manner to either walk around or fix this "issue"?

**Comment by ljharb** [comment]
In your eslint config, set `env: { jest: true }`. It's got nothing to do with eslint-nibble.

**Comment by brunolnetto** [comment]
Great!
