### ISSUE TITLE
Global ESLint on Windows: Allow passing through `--resolve-plugins-relative-to`

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [IanVS/eslint-nibble#98]
On Windows, the only way I can get plugins to resolve with my global installation of ESLint is by passing the option `--resolve-plugins-relative-to`, set to the output of `npm root -g`. Unfortunately `eslint-nibble` does not recognize this option, so I can't use it on Windows.

**Comment by IanVS** [comment]
Hi @ehoogeveen-medweb, that sounds fine to me, would you be willing to submit a PR?  You could use this PR as a guide.  https://github.com/IanVS/eslint-nibble/pull/76/files

**Comment by ljharb** [comment]
Note that using eslint globally is heavily deprecated by the eslint team, and has always been a bad idea.

**Comment by IanVS** [comment]
Published in 8.1.0.  Thanks!
